# Generated by Django 4.2.5 on 2023-09-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('student_num', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('course', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.college')),
            ],
        ),
    ]
